Resources:
  VpcCurso:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcCurso
      CidrBlock: 10.0.1.0/24

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcCurso
      CidrBlock: 10.0.2.0/24

  SubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcCurso
      CidrBlock: 10.0.3.0/24
